/**
* This file is autogenerated. Please do not edit it
*/
( function ( w ) {
  var deepExtend = function ( out ) {
    out = out || { };

    for (var i = 1; i < arguments.length; i++) {
      var obj = arguments[ i ];

      if ( !obj ) {
        continue;
      }

      for (var key in obj) {
        if ( obj.hasOwnProperty( key ) ) {
          if ( typeof obj[ key ] === 'object' ) {
            deepExtend( out[ key ], obj[ key ] );
          }
          else {
            out[ key ] = obj[ key ];
          }
        }
      }
    }

    return out;
  };

  w.__i18n = w.__i18n || {};
  w.__i18n = deepExtend( w.__i18n, [ [FILE_CONTENTS] ] );
}( window ));
